services:
  mandat:
    build: .
    restart: unless-stopped
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.mandat.rule=Host(`${APP_DOMAIN}`)
      - traefik.http.routers.mandat.entrypoints=websecure
      - traefik.http.routers.mandat.tls.certresolver=letsencrypt
      - traefik.http.services.mandat.loadbalancer.server.port=80

networks:
  web:
    external: true
